spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Desktop/food-delivery/config-repo
          default-label: main
          force-pull: true
          skip-ssl-validation: true
          strict-host-key-checking: false
          clone-on-start: true
        native:
          search-locations: file:///config-repo


server:
  port: 8888